services:
  # Backend API Service
  - type: web
    name: youtube-clone-backend
    runtime: node
    region: oregon
    plan: free
    branch: main
    rootDir: backend
    buildCommand: npm install && npm run build && npm run db:migrate
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        sync: false # Set this in Render dashboard (your existing PostgreSQL URL)
      - key: SESSION_SECRET
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        sync: false # Will be: https://your-frontend-name.onrender.com
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: GITHUB_CALLBACK_URL
        sync: false # Will be: https://your-backend-name.onrender.com/api/auth/github/callback

  # Frontend Static Site
  - type: web
    name: youtube-clone-frontend
    runtime: static
    region: oregon
    plan: free
    branch: main
    rootDir: frontend-web
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        sync: false # Will be: https://your-backend-name.onrender.com/api
      - key: REACT_APP_SOCKET_URL
        sync: false # Will be: https://your-backend-name.onrender.com
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
